name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker compose service
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
        run: |
          docker-compose build
          docker-compose push
